apiVersion: kaas.mirantis.com/v1alpha1
kind: KaaSRelease
metadata:
  name: kaas-2-0-0
spec:
  version: 2.0.0
  clusterRelease: ucp-5-7-0-3-3-3
  supportedClusterReleases:
  - version: 5.7.0
    name: ucp-5-7-0-3-3-3
  - version: 6.7.0
    name: mosk-6-7-0
    tag: dev
  bootstrap:
    version: 1.10.12
  helmRepositories:
  - name: kaas-release
    url: core/helm
  - name: kaas-iam
    url: iam/helm
  - name: kaas-bm
    url: bm/helm
  management:
    helmReleases:
    - name: iam
      requiresPersistentVolumes: true
      requires:
      - local-volume-provisioner
      localVolumes:
      - name: kaas-iam-data
        bindMounts:
        - volPerNode: 1
      version: 1.1.16
      chart: kaas-iam/iam
      namespace: kaas
      values:
        api:
          # Set during bootstrap
          # keycloak:
          #   url:
          #   ca:
          tls:
            enabled: true
          service:
            type: LoadBalancer
            # Set during bootstrap
            # loadBalancerIP:
        keycloak:
          keycloak:
            service:
              type: LoadBalancer
              # Set during bootstrap
              # loadBalancerIP:
            pvc:
              enabled: true
            extraVolumes: |
              - name: tls
                secret:
                  secretName: keycloak-tls-certs
            extraVolumeMounts: |
              - name: tls
                mountPath: "/etc/x509/https"
          mariadb:
            volume:
              class_name: iam-kaas-iam-data
    - name: kaas-ui
      version: 1.10.12
      chart: kaas-release/kaas-ui
      namespace: kaas
      values:
        image:
          tag: 1.10.12
        rbac:
          create: true

    - name: iam-controller
      version: 1.10.12
      chart: kaas-release/iam-controller
      namespace: kaas
      values:
        image:
          tag: 1.10.12

    - name: admission-controller
      version: 1.10.12
      chart: kaas-release/admission-controller
      namespace: kaas
      values:
        image:
          tag: 1.10.12

    - name: release-controller
      version: 1.10.12
      chart: kaas-release/release-controller
      namespace: kaas
      values:
        image:
          tag: 1.10.12

    - name: kaas-exporter
      version: 1.10.12
      chart: kaas-release/kaas-exporter
      namespace: kaas
      values:
        image:
          tag: 1.10.12

    - name: kaas-public-api
      version: 1.10.12
      chart: kaas-release/kaas-public-api
      namespace: kaas
      values: {}

  regional:
  - provider: openstack
    helmReleases:
    - name: openstack-provider
      version: 1.10.12
      chart: kaas-release/openstack-provider
      namespace: kaas
      values:
        images:
          openstackMachineController:
            tag: 1.10.12
    - &lcmController
      name: lcm-controller
      version: 1.10.12
      chart: kaas-release/lcm-controller
      namespace: kaas
      values:
        lcmControllerImage:
          tag: v0.2.0-149-g412c5a05
    - name: os-credentials-controller
      version: 1.10.12
      chart: kaas-release/os-credentials-controller
      namespace: kaas
      values:
        image:
          tag: 1.10.12
  - provider: baremetal
    helmReleases:
      - name: baremetal-operator
        requiresPersistentVolumes: true
        version: 3.0.7
        chart: kaas-bm/baremetal-operator
        namespace: kaas
        values:
          init_bootstrap:
            provisioning_files:
              ansible.tar.gz: bm/bin/ansible/provisioning_ansible-0.1.1-19-31add35.tgz
              ansible.tar.gz.md5sum: bm/bin/ansible/provisioning_ansible-0.1.1-19-31add35.tgz.md5sum
          baremetal_operator:
            image:
              tag: base-bionic-20200812172956
      - name: baremetal-provider
        version: 1.10.12
        chart: kaas-release/baremetal-provider
        namespace: kaas
        values:
          cluster_api_provider_baremetal:
            image:
              tag: 1.10.12
      - name: kaas-ipam
        version: 3.0.7
        chart: kaas-bm/kaas-ipam
        namespace: kaas
        values: {}
      - *lcmController
  - provider: aws
    helmReleases:
      - name: aws-provider
        version: 1.10.12
        chart: kaas-release/aws-provider
        namespace: kaas
        values:
          awsController:
            image:
              tag: 1.10.12
      - *lcmController
      - name: aws-credentials-controller
        version: 1.10.12
        chart: kaas-release/aws-credentials-controller
        namespace: kaas
        values:
          image:
            tag: 1.10.12
  - provider: byo
    helmReleases:
      - name: byo-provider
        version: 1.10.12
        chart: kaas-release/byo-provider
        namespace: kaas
        values:
          byoController:
            image:
              tag: 1.10.12
      - name: byo-credentials-controller
        version: 1.10.12
        chart: kaas-release/byo-credentials-controller
        namespace: kaas
        values:
          image:
            tag: 1.10.12
