apiVersion: kaas.mirantis.com/v1alpha1
kind: KaaSRelease
metadata:
  name: kaas-2-4-0
spec:
  version: 2.4.0
  clusterRelease: mke-5-11-0-3-3-4
  supportedClusterReleases:
  - version: 5.10.0
    name: mke-5-10-0-3-3-4
    availableUpgrades:
    - version: 5.11.0
  - version: 5.11.0
    name: mke-5-11-0-3-3-4
  - version: 6.10.0
    name: mosk-6-10-0
    tag: openstack
  bootstrap:
    version: 1.16.1
  helmRepositories:
  - name: kaas-release
    url: core/helm
  - name: kaas-iam
    url: iam/helm
  - name: kaas-bm
    url: bm/helm
  management:
    helmReleases:
    - name: iam
      requires:
      - local-volume-provisioner
      localVolumes:
      - name: kaas-iam-data
        bindMounts:
        - volPerNode: 1
      version: 1.2.1
      chart: kaas-iam/iam
      namespace: kaas
      values:
        api:
          # Set during bootstrap
          # keycloak:
          #   url:
          #   ca:
          tls:
            enabled: true
          service:
            type: LoadBalancer
            # Set during bootstrap
            # loadBalancerIP:
        keycloak:
          keycloak:
            service:
              type: LoadBalancer
              # Set during bootstrap
              # loadBalancerIP:
            pvc:
              enabled: true
            extraVolumes: |
              - name: tls
                secret:
                  secretName: keycloak-tls-certs
            extraVolumeMounts: |
              - name: tls
                mountPath: "/etc/x509/https"
          mariadb:
            volume:
              class_name: iam-kaas-iam-data
    - name: kaas-ui
      version: 1.16.1
      chart: kaas-release/kaas-ui
      namespace: kaas
      values:
        image:
          tag: 1.16.2
        rbac:
          create: true

    - name: iam-controller
      version: 1.16.1
      chart: kaas-release/iam-controller
      namespace: kaas
      values:
        image:
          tag: 1.16.1

    - name: admission-controller
      version: 1.16.1
      chart: kaas-release/admission-controller
      namespace: kaas
      values:
        image:
          tag: 1.16.1

    - name: release-controller
      version: 1.16.1
      chart: kaas-release/release-controller
      namespace: kaas
      values:
        image:
          tag: 1.16.1

    - name: kaas-exporter
      version: 1.16.1
      chart: kaas-release/kaas-exporter
      namespace: kaas
      values:
        image:
          tag: 1.16.1

    - name: kaas-public-api
      version: 1.16.1
      chart: kaas-release/kaas-public-api
      namespace: kaas
      values: {}

    - name: baremetal-public-api
      version: 3.1.7
      chart: kaas-bm/baremetal-public-api
      namespace: kaas
      requiresPersistentVolumes: true
      values: {}

    - name: proxy-controller
      version: 1.16.1
      chart: kaas-release/proxy-controller
      namespace: kaas
      values:
        image:
          tag: 1.16.1
  regional:
  - provider: openstack
    helmReleases:
    - name: openstack-provider
      version: 1.16.1
      chart: kaas-release/openstack-provider
      namespace: kaas
      values:
        images:
          openstackMachineController:
            tag: 1.16.1
    - &lcmController
      name: lcm-controller
      version: 1.16.1
      chart: kaas-release/lcm-controller
      namespace: kaas
      values:
        lcmControllerImage:
          tag: v0.2.0-224-g5c413d37
    - name: os-credentials-controller
      version: 1.16.1
      chart: kaas-release/os-credentials-controller
      namespace: kaas
      values:
        image:
          tag: 1.16.1
  - provider: baremetal
    helmReleases:
      - name: baremetal-operator
        requiresPersistentVolumes: true
        version: 3.1.7
        chart: kaas-bm/baremetal-operator
        namespace: kaas
        values: {}
      - name: baremetal-provider
        version: 1.16.1
        chart: kaas-release/baremetal-provider
        namespace: kaas
        values:
          cluster_api_provider_baremetal:
            image:
              tag: 1.16.4
      - name: kaas-ipam
        version: 3.1.7
        chart: kaas-bm/kaas-ipam
        namespace: kaas
        values:
          kaas_ipam:
            image:
              tag: base-bionic-20201210175212
      - *lcmController
  - provider: aws
    helmReleases:
      - name: aws-provider
        version: 1.16.1
        chart: kaas-release/aws-provider
        namespace: kaas
        values:
          awsController:
            image:
              tag: 1.16.1
      - *lcmController
      - name: aws-credentials-controller
        version: 1.16.1
        chart: kaas-release/aws-credentials-controller
        namespace: kaas
        values:
          image:
            tag: 1.16.1
  - provider: byo
    helmReleases:
      - name: byo-provider
        version: 1.16.1
        chart: kaas-release/byo-provider
        namespace: kaas
        values:
          byoController:
            image:
              tag: 1.16.1
      - name: byo-credentials-controller
        version: 1.16.1
        chart: kaas-release/byo-credentials-controller
        namespace: kaas
        values:
          image:
            tag: 1.16.1
  - provider: vsphere
    helmReleases:
      - name: vsphere-provider
        version: 1.16.1
        chart: kaas-release/vsphere-provider
        namespace: kaas
        values:
          vsphere_provider:
            image:
              tag: 1.16.1
      - name: vsphere-credentials-controller
        version: 1.16.1
        chart: kaas-release/vsphere-credentials-controller
        namespace: kaas
        values:
          image:
            tag: 1.16.4
      - *lcmController
