apiVersion: kaas.mirantis.com/v1alpha1
kind: KaaSRelease
metadata:
  name: kaas-2-8-0
spec:
  version: 2.8.0
  clusterRelease: mke-5-15-0-3-3-6
  supportedClusterReleases:
  - version: 5.11.0
    name: mke-5-11-0-3-3-4
    availableUpgrades:
    - version: 5.15.0
    providers:
      supported:
      - byo
  - version: 5.14.0
    name: mke-5-14-0-3-3-6
    availableUpgrades:
    - version: 5.15.0
  - version: 5.15.0
    name: mke-5-15-0-3-3-6
  - version: 6.14.0
    name: mos-6-14-0-21-2
    tag: openstack
  bootstrap:
    version: 1.20.2
  helmRepositories:
  - name: kaas-iam
    url: iam/helm
  - name: kaas-bm
    url: bm/helm
  management:
    helmReleases:
    - name: iam
      requires:
      - local-volume-provisioner
      localVolumes:
      - name: kaas-iam-data
        bindMounts:
        - volPerNode: 1
      version: 2.3.0
      chart: kaas-iam/iam
      namespace: kaas
      values:
        api:
          # Set during bootstrap
          # keycloak:
          #   url:
          #   ca:
          tls:
            enabled: true
          service:
            type: LoadBalancer
            # Set during bootstrap
            # loadBalancerIP:
        keycloak:
          keycloak:
            service:
              type: LoadBalancer
              # Set during bootstrap
              # loadBalancerIP:
            pvc:
              enabled: true
            extraVolumes: |
              - name: tls
                secret:
                  secretName: keycloak-tls-certs
            extraVolumeMounts: |
              - name: tls
                mountPath: "/etc/x509/https"
          mariadb:
            volume:
              class_name: iam-kaas-iam-data
    - name: kaas-ui
      chartURL: core/helm/kaas-ui-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values:
        image:
          tag: 1.20.2
        rbac:
          create: true

    - name: iam-controller
      chartURL: core/helm/iam-controller-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values:
        image:
          tag: 1.20.2

    - name: admission-controller
      chartURL: core/helm/admission-controller-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values:
        image:
          tag: 1.20.2

    - name: release-controller
      chartURL: core/helm/release-controller-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values:
        image:
          tag: 1.20.2

    - name: kaas-exporter
      chartURL: core/helm/kaas-exporter-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values:
        image:
          tag: 1.20.2

    - name: kaas-public-api
      chartURL: core/helm/kaas-public-api-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values: {}

    - name: baremetal-public-api
      version: 4.1.3
      chart: kaas-bm/baremetal-public-api
      namespace: kaas
      requiresPersistentVolumes: true
      values: {}

    - name: proxy-controller
      chartURL: core/helm/proxy-controller-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values:
        image:
          tag: 1.20.2

    - name: rhellicense-controller
      chartURL: core/helm/rhellicense-controller-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values:
        image:
          tag: 1.20.2

  regional:
  - provider: openstack
    helmReleases:
    - name: openstack-provider
      chartURL: core/helm/openstack-provider-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values:
        images:
          openstackMachineController:
            tag: 1.20.2
    - &squidProxy
      name: squid-proxy
      chartURL: core/helm/squid-proxy-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values:
        image:
          tag: 0.0.1-3
    - &lcmController
      name: lcm-controller
      chartURL: core/helm/lcm-controller-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values:
        lcmControllerImage:
          tag: v0.2.0-327-g5676f4e3
    - &mcc-cache
      name: mcc-cache
      chartURL: core/helm/mcc-cache-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      requires:
      - local-volume-provisioner
      localVolumes:
      - name: kaas-nginx-data
        bindMounts:
        - volPerNode: 1
      values:
        nginx:
          image:
            tag: 1.18.0
          volume:
            enabled: true
            storageClass: mcc-cache-kaas-nginx-data
        registry:
          image:
            tag: 2.7.1
        kproxy:
          image:
            tag: 1.20.2
    - name: os-credentials-controller
      chartURL: core/helm/os-credentials-controller-1.20.2.tgz
      version: 1.20.2
      namespace: kaas
      values:
        image:
          tag: 1.20.2
  - provider: baremetal
    helmReleases:
      - name: baremetal-operator
        requiresPersistentVolumes: true
        version: 4.1.3
        chart: kaas-bm/baremetal-operator
        namespace: kaas
        values: {}
      - name: baremetal-provider
        chartURL: core/helm/baremetal-provider-1.20.2.tgz
        version: 1.20.2
        namespace: kaas
        values:
          cluster_api_provider_baremetal:
            image:
              tag: 1.20.2
      - name: kaas-ipam
        version: 4.1.3
        chart: kaas-bm/kaas-ipam
        namespace: kaas
        values: {}
      - *lcmController
      - *mcc-cache
      - *squidProxy
  - provider: aws
    helmReleases:
      - name: aws-provider
        chartURL: core/helm/aws-provider-1.20.2.tgz
        version: 1.20.2
        namespace: kaas
        values:
          awsController:
            image:
              tag: 1.20.2
      - *lcmController
      - *mcc-cache
      - *squidProxy
      - name: aws-credentials-controller
        chartURL: core/helm/aws-credentials-controller-1.20.2.tgz
        version: 1.20.2
        namespace: kaas
        values:
          image:
            tag: 1.20.2
  - provider: byo
    helmReleases:
      - name: byo-provider
        chartURL: core/helm/byo-provider-1.20.2.tgz
        version: 1.20.2
        namespace: kaas
        values:
          byoController:
            image:
              tag: 1.20.2
      - name: byo-credentials-controller
        chartURL: core/helm/byo-credentials-controller-1.20.2.tgz
        version: 1.20.2
        namespace: kaas
        values:
          image:
            tag: 1.20.2
  - provider: vsphere
    helmReleases:
      - name: vsphere-provider
        chartURL: core/helm/vsphere-provider-1.20.2.tgz
        version: 1.20.2
        namespace: kaas
        values:
          vsphere_provider:
            image:
              tag: 1.20.2
      - name: vsphere-credentials-controller
        chartURL: core/helm/vsphere-credentials-controller-1.20.2.tgz
        version: 1.20.2
        namespace: kaas
        values:
          image:
            tag: 1.20.2
      - name: kaas-ipam
        version: 4.1.3
        chart: kaas-bm/kaas-ipam
        namespace: kaas
        values: {}
      - *lcmController
      - *mcc-cache
      - *squidProxy
  - provider: equinixmetal
    helmReleases:
      - name: equinix-provider
        chartURL: core/helm/equinix-provider-1.20.2.tgz
        version: 1.20.2
        namespace: kaas
        values:
          equinixController:
            image:
              tag: 1.20.2
      - name: equinix-credentials-controller
        chartURL: core/helm/equinix-credentials-controller-1.20.2.tgz
        version: 1.20.2
        namespace: kaas
        values:
          image:
            tag: 1.20.2
      - *lcmController
      - *mcc-cache
      - *squidProxy
