apiVersion: kaas.mirantis.com/v1alpha1
kind: ClusterRelease
metadata:
  name: mosk-6-7-0
spec:
  lcmType: ucp
  version: 6.7.0
  description: |
    kubernetes: 1.18.8
    containerd: 1.3.4
    docker-engine: ee-stable-19.03.12
    coredns: 1.5.0
    etcd: v3.4.3
    calico: v3.14.1
    openstack-operator: 0.3.3
    tungstenfabric-operator: 0.0.7
  releaseNotes:
  - version: 6.7.0
    notes:
    - text: Internal Dev version, KaaS cluster release 5.7.0 + MOSK
  helm:
    repositories:
    - name: kaas
      url: core/helm
    - name: stacklight
      url: stacklight/helm
    - name: kaas-bm
      url: bm/helm
    - name: ceph
      url: ceph/helm
    - name: openstack-controller
      url: openstack/helm/openstack-controller
    - name: redis
      url: openstack/helm/redis-operator
    - name: tf
      url: tungsten/helm
    releases:
    - chart: kaas/metallb
      name: metallb
      namespace: metallb-system
      version: 1.10.12
      values:
        configInline:
          address-pools:
          - addresses:
            - 192.168.66.240-192.168.66.250
            name: default
            protocol: layer2
    - name: stacklight
      chart: stacklight/stacklight
      version: 0.1.2-mcp-285
      namespace: stacklight
      requiresPersistentVolumes: true
      requires:
      - local-volume-provisioner
      localVolumes:
      - name: elasticsearch-data
        bindMounts:
        - volPerNode: 1
      - name: prometheus-data
        bindMounts:
        - volPerNode: 1
      - name: alertmanager-data
        bindMounts:
        - volPerNode: 1
      - name: postgresql-db
        bindMounts:
        - volPerNode: 1
      values:
        createHelmBundleCRD: true
        tillerImage: lcm/helm/tiller:v2.16.9-39
        helmControllerImage: lcm/lcm-controller:v0.2.0-149-g412c5a05
        nginxExporter:
          enabled: false
        platform: ucp
        ucp:
          enabled: true
        logging:
          enabled: false
        helm:
          dedicatedHelmController: false
      required: true
    - name: ceph-controller
      chart: ceph/ceph-operator
      version: 1.0.0-mcp-16
      namespace: ceph
      values:
        images:
          cephController:
            repository: ceph/mcp/ceph-controller
            tag: v1.0.0-20200805103414
      required: true
    - name: local-volume-provisioner
      chart: kaas-bm/local-volume-provisioner
      version: 1.0.4-mcp
      namespace: kube-system
      values: {}
    - name: metrics-server
      version: 1.10.12
      chart: kaas/metrics-server
      namespace: kube-system
      values:
        image:
          tag: v0.3.6-1
      required: true
    - name: descheduler
      version: 1.10.12
      chart: kaas/descheduler
      namespace: kube-system
      values:
        image:
          tag: v0.8.0
      required: true
    - name: openstack-operator
      chart: openstack-controller/openstack-operator
      version: 0.3.3
      namespace: osh-system
      values:
        image:
          tag: 0.3.3
      required: true
      requiresPersistentVolumes: true
      requires:
      - local-volume-provisioner
      localVolumes:
      - name: bind-mounts
        bindMounts:
        # mariadb - 1 openstack-control-plane=enabled
        # etcd-coordination - 1 openstack-control-plane=enabled
        # redis-telemetry - 1 openstack-control-plane=enabled
        - volPerNode: 3
    - name: os-redis-operator
      chart: redis/redisoperator
      version: 3.1.0
      namespace: openstack-redis
      values:
        image: docker-kaas-local.artifactory.mirantis.com/openstack/extra/redis-operator
        rbac:
          apiVersion: v1
          install: true
        tag: v1.0.0
      required: true
    - chart: tf/tungstenfabric-operator
      name: tungstenfabric-operator
      version: 0.0.7
      namespace: tf
      values: {}
      required: true
  agent:
    version: v0.2.0-149-g412c5a05
    downloadURL: lcm/bin/lcm-agent/v0.2.0-149-g412c5a05/lcm-agent
    sha256: 8679b744bfdb755152ef1ed2c62217ae9cd54df3fe916fb093d31064b26173f3
  images:
    helmController: lcm/lcm-controller:v0.2.0-149-g412c5a05
    tiller: lcm/helm/tiller:v2.16.9-39
    ucpSourceRepo: lcm/docker
    ucpTargetRepo: docker
  machineTypes:
    worker:
    - &downloadLcmAnsible
      name: download lcm ansible
      params:
        path: /root/lcm-ansible-v0.2.0-110-g63cf88b-1
        url: lcm/bin/lcm-ansible/v0.2.0-110-g63cf88b/lcm-ansible.tar.gz
        sha256: ecade5e6db50a1ed76d3b26e3582c47362058df545b1be0a4e21dd35f1befbec
      runner: downloader
      version: "1"
      phase: prepare
    - &downloadAnsibleDocker
      name: download ansible docker
      params:
        path: /root/lcm-ansible-v0.2.0-110-g63cf88b-1/ansible-docker
        url: lcm/bin/ansible-docker/v0.3.5-136-g38653c7/ansible-docker.tar.gz
        sha256: cf7fdbb17a3e95bf429af9b3175ece2e962e93a1244ab2b8d3a99efbc3af8351
      runner: downloader
      version: "1"
      phase: prepare
    - &setup
      name: setup
      params:
        script: /root/lcm-ansible-v0.2.0-110-g63cf88b-1/setup.sh
        kaas_ubuntu_repo: kaas/ubuntu-2020-07-30-013349
      runner: bash
      version: "1"
      phase: prepare
    - &preDownload
      name: pre download
      params:
        ansible: /usr/bin/ansible-playbook
        inventoryTemplate: /root/lcm-ansible-v0.2.0-110-g63cf88b-1/inventory/inventory-docker.tmpl
        playbook: /root/lcm-ansible-v0.2.0-110-g63cf88b-1/download_ucp.yml
        ucp_pre_pull_images: "true"
        controlNodeIP: "{{ .ControlNodeIP }}"
        ucp_enable_admin_ucp_scheduling: "{{ not .IsDedicatedMaster }}"
        ucp_tag: 3.3.3
        docker_engine_version: "{ Debian: ee-stable-19.03.12, RedHat: ee-stable-19.03.12 }"
      phase: prepare
      runner: ansible
      version: "1"
    - &deploy
      name: deploy
      params:
        playbook: /root/lcm-ansible-v0.2.0-110-g63cf88b-1/reconcile.yml
        ansible: /usr/bin/ansible-playbook
        inventoryTemplate: /root/lcm-ansible-v0.2.0-110-g63cf88b-1/inventory/inventory-docker.tmpl
        controlNodeIP: "{{ .ControlNodeIP }}"
        ucp_enable_admin_ucp_scheduling: "{{ not .IsDedicatedMaster }}"
        ucp_tag: 3.3.3
        docker_engine_version: "{ Debian: ee-stable-19.03.12, RedHat: ee-stable-19.03.12 }"
      runner: ansible
      version: "1"
      phase: deploy
    control:
    - *downloadLcmAnsible
    - *downloadAnsibleDocker
    - *setup
    - *preDownload
    - *deploy
